
-- Generated by ORDS REST Data Services 23.2.3.r2421937
-- Schema: DEMO  Date: Wed Sep 13 09:26:25 2023 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DEMO',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'demo',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'ujs',
      p_base_path      => '/ujs/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ujs',
      p_pattern        => 'lov/:appid/:lovname',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ujs',
      p_pattern        => 'lov/:appid/:lovname',
      p_method         => 'GET',
      p_source_type    => 'resource/lob',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'select ''text/html'', 
replace(
    replace(gen_initjs(:appid,:lovname), chr(10), ''<BR>''
    ),
    chr(9), ''&nbsp;&nbsp;&nbsp;&nbsp;''
)
 from dual  ');

    
        
COMMIT;

END;